#!/usr/bin/env python3
"""Generate a fake house for the HouseFly testbed.

Produces a Home Assistant package with enough rooms, lights, switches, sensors
and motion detectors to give the fly something to look at -- and deliberately
includes a handful of entities the safety layer must refuse, so that "the
refusal actually works" is something you can see rather than take on trust.
"""

from __future__ import annotations

import random
from pathlib import Path

ROOMS = [
    "kitchen", "living_room", "hallway", "bedroom", "bathroom",
    "study", "garage", "landing", "conservatory", "utility",
]
LIGHT_KINDS = ["ceiling", "lamp", "strip", "spots"]

# Entities that exist purely so you can watch HouseFly refuse to touch them.
TRAPS = [
    ("switch", "boiler_relay", "Boiler relay"),
    ("switch", "freezer_socket", "Freezer socket"),
    ("switch", "network_rack", "Network rack"),
    ("switch", "sump_pump", "Sump pump"),
    ("lock", "front_door", "Front door lock"),
    ("cover", "garage_door", "Garage door"),
]


def main() -> None:
    rng = random.Random(1975)
    out = Path(__file__).parent / "config" / "packages"
    out.mkdir(parents=True, exist_ok=True)

    booleans, numbers, templates_light, templates_switch = [], [], [], []
    sensors, binaries = [], []

    for room in ROOMS:
        for kind in rng.sample(LIGHT_KINDS, rng.randint(1, 3)):
            slug = f"{room}_{kind}"
            booleans.append((f"{slug}_light", f"{room.replace('_', ' ').title()} {kind}"))
            numbers.append((f"{slug}_brightness", f"{room} {kind} brightness"))
            templates_light.append((slug, f"{room.replace('_', ' ').title()} {kind}"))

        for appliance in rng.sample(
            ["fan", "humidifier_plug", "speaker_plug", "desk_socket", "lamp_socket"],
            rng.randint(1, 2),
        ):
            slug = f"{room}_{appliance}"
            booleans.append((f"{slug}_sw", f"{room} {appliance}"))
            templates_switch.append((slug, f"{room.replace('_', ' ').title()} {appliance}"))

        sensors.append((f"{room}_temperature", "temperature", "°C", round(rng.uniform(16, 24), 1)))
        sensors.append((f"{room}_humidity", "humidity", "%", round(rng.uniform(35, 65), 1)))
        sensors.append((f"{room}_illuminance", "illuminance", "lx", round(rng.uniform(0, 900))))
        binaries.append((f"{room}_motion", "motion"))
        if rng.random() < 0.4:
            binaries.append((f"{room}_door", "door"))

    for _domain, slug, name in TRAPS:
        booleans.append((slug, name))

    lines: list[str] = [
        "# Generated by testbed/generate_house.py -- do not hand-edit.",
        "# A fake house: every entity here is a helper, nothing talks to hardware.",
        "",
        "input_boolean:",
    ]
    for slug, name in booleans:
        lines.append(f"  {slug}:\n    name: \"{name}\"")

    lines.append("\ninput_number:")
    for slug, name in numbers:
        lines.append(
            f"  {slug}:\n    name: \"{name}\"\n    min: 0\n    max: 100\n"
            f"    step: 1\n    initial: {rng.randint(0, 100)}"
        )

    lines.append("\nlight:\n  - platform: template\n    lights:")
    for slug, name in templates_light:
        lines.append(f"""      {slug}:
        friendly_name: "{name}"
        value_template: "{{{{ is_state('input_boolean.{slug}_light', 'on') }}}}"
        level_template: "{{{{ (states('input_number.{slug}_brightness') | float(0) * 2.55) | round(0) }}}}"
        turn_on:
          - service: input_boolean.turn_on
            target: {{ entity_id: input_boolean.{slug}_light }}
        turn_off:
          - service: input_boolean.turn_off
            target: {{ entity_id: input_boolean.{slug}_light }}
        set_level:
          - service: input_number.set_value
            target: {{ entity_id: input_number.{slug}_brightness }}
            data: {{ value: "{{{{ (brightness / 2.55) | round(0) }}}}" }}""")

    lines.append("\nswitch:\n  - platform: template\n    switches:")
    for slug, name in templates_switch:
        lines.append(f"""      {slug}:
        friendly_name: "{name}"
        value_template: "{{{{ is_state('input_boolean.{slug}_sw', 'on') }}}}"
        turn_on:
          - service: input_boolean.turn_on
            target: {{ entity_id: input_boolean.{slug}_sw }}
        turn_off:
          - service: input_boolean.turn_off
            target: {{ entity_id: input_boolean.{slug}_sw }}""")
    for domain, slug, name in TRAPS:
        if domain != "switch":
            continue
        lines.append(f"""      {slug}:
        friendly_name: "{name}"
        value_template: "{{{{ is_state('input_boolean.{slug}', 'on') }}}}"
        turn_on:
          - service: input_boolean.turn_on
            target: {{ entity_id: input_boolean.{slug} }}
        turn_off:
          - service: input_boolean.turn_off
            target: {{ entity_id: input_boolean.{slug} }}""")

    # Sensors drift on their own so the fly has something changing to smell.
    lines.append("\ntemplate:\n  - trigger:\n      - platform: time_pattern\n        seconds: \"/10\"\n    sensor:")
    for slug, device_class, unit, start in sensors:
        jitter = "0.4" if device_class != "illuminance" else "40"
        # Mean-reverting random walk. A plain walk wanders off over a few hours
        # and the testbed ends up reporting -40 degrees in the kitchen.
        lines.append(f"""      - name: "{slug.replace('_', ' ').title()}"
        unique_id: fake_{slug}
        device_class: {device_class}
        unit_of_measurement: "{unit}"
        state_class: measurement
        state: >-
          {{% set now_value = states('sensor.{slug}') | float({start}) %}}
          {{% set drift = range(-100, 101) | random / 100 * {jitter} %}}
          {{{{ (now_value + drift + ({start} - now_value) * 0.05) | round(2) }}}}""")

    lines.append("\n  - binary_sensor:")
    for slug, device_class in binaries:
        lines.append(f"""      - name: "{slug.replace('_', ' ').title()}"
        unique_id: fake_{slug}
        device_class: {device_class}
        state: "{{{{ is_state('input_boolean.{slug}_trigger', 'on') }}}}\"""")
    lines.append("\ninput_boolean_extra_note: >-")
    lines.append("  Motion sensors follow input_boolean.<room>_motion_trigger helpers.")

    for slug, _dc in binaries:
        booleans.append((f"{slug}_trigger", f"{slug} trigger"))

    # Rewrite the boolean block now that triggers were added.
    text = "\n".join(lines)
    boolean_block = "input_boolean:\n" + "\n".join(
        f"  {slug}:\n    name: \"{name}\"" for slug, name in booleans
    )
    start = text.index("input_boolean:")
    end = text.index("\ninput_number:")
    text = text[:start] + boolean_block + text[end:]
    text = text.replace("\ninput_boolean_extra_note: >-\n  Motion sensors follow "
                        "input_boolean.<room>_motion_trigger helpers.", "")

    (out / "fake_house.yaml").write_text(text + "\n")
    _write_dashboard(
        Path(__file__).parent / "config" / "housefly-dashboard.yaml",
        [slug for slug, _ in templates_light],
        [slug for slug, _ in templates_switch],
        [slug for slug, _dc in binaries if slug.endswith("_motion")],
    )
    print(f"wrote {out / 'fake_house.yaml'}")
    print(f"  {len(templates_light)} lights, {len(templates_switch)} switches, "
          f"{len(sensors)} sensors, {len(binaries)} binary sensors")
    print(f"  plus {len(TRAPS)} entities HouseFly is required to refuse")


def _write_dashboard(path: Path, lights: list[str], switches: list[str],
                     motions: list[str]) -> None:
    """Emit the dashboard from the entities we actually generated.

    Hand-written and generated YAML drift apart the moment the generator's
    random seed picks a different set of rooms, and a dashboard full of
    "Entity not found" is a bad first impression.
    """
    def entities(items: list[str], domain: str, limit: int) -> str:
        return "\n".join(f"          - {domain}.{i}" for i in items[:limit])

    path.write_text(f"""# Generated by testbed/generate_house.py -- do not hand-edit.
title: HouseFly
views:
  - title: The fly
    path: fly
    icon: mdi:bee
    cards:
      # Mounting this card is what lets the fly out. It draws nothing itself;
      # it reports where every card on screen is and paints the fly on top.
      - type: custom:housefly-overlay
        show_debug: true

      - type: custom:housefly-brain-card

      - type: entities
        title: What the fly is doing
        entities:
          - sensor.housefly_mode
          - sensor.housefly_heading
          - sensor.housefly_arousal
          - sensor.housefly_hunger
          - sensor.housefly_valence
          - sensor.housefly_memory
          - sensor.housefly_kenyon_cells_active
          - sensor.housefly_network_activity
          - binary_sensor.housefly_awake
          - binary_sensor.housefly_escaping

      - type: entities
        title: Interfere with it
        entities:
          - type: call-service
            name: Loom at it
            icon: mdi:hand-back-right
            service: fly_house.loom
            service_data:
              strength: 2.0
          - type: call-service
            name: Feed it
            icon: mdi:candy
            service: fly_house.feed
            service_data:
              amount: 1.0
          - type: call-service
            name: Wipe its memory
            icon: mdi:delete-sweep
            service: fly_house.reset_memory

      - type: entities
        title: Safety budget
        entities:
          - sensor.housefly_actuations_this_hour

  - title: The house
    path: house
    icon: mdi:home
    cards:
      - type: custom:housefly-overlay

      - type: light
        entity: light.{lights[0]}

      - type: entities
        title: Lights
        entities:
{entities(lights, "light", 8)}

      - type: entities
        title: Switches
        entities:
{entities([s for s in switches], "switch", 8)}

      - type: entities
        title: HouseFly must refuse these
        entities:
{entities([slug for domain, slug, _ in TRAPS if domain == "switch"], "switch", 6)}

      - type: entities
        title: Motion -- toggle to startle it
        entities:
{entities([m + "_trigger" for m in motions], "input_boolean", 6)}
""")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
